### ISSUE TITLE
Add collection of stories

### ISSUE THREAD

**Issue by vsoch** [good-labs/greater-good-affirmation#1]
The stories folder should have real (provided by the developer, publicly) or example user stories for projects that are for the greater good. This will be an important resource if a contributor comes to the repository and wants to understand the kind of projects that would be able / not be able to take the pledge.

**Comment by pdurbin** [comment]
I'm confused. Stories are being added to the other repo such as in pull request https://github.com/good-labs/good-labs.github.io/pull/16 ? Right? Or do we want stories in this repo too?

**Comment by vsoch** [comment]
This was an old issue I think I transferred, not relevant anymore. Correct, they go in the other repo.
