### ISSUE TITLE
maintainer or final decision maker

### ISSUE THREAD

**Issue by pdurbin** [good-labs/greater-good-affirmation#11]
As of 562ba07 the pledge starts with "As a maintainer of an open source project or group" but in my world I'm a maintainer of some software but not one of the final decision makers. Should we change the phrasing?

**Comment by vsoch** [comment]
Definitely, what would you suggest? I do think it has to be someone that feels like they can speak for the project, no?

**Comment by pdurbin** [comment]
Maybe "project leader" but I really don't know. Projects vary, obviously.

**Comment by vsoch** [comment]
Does what I put fit better now?

**Comment by pdurbin** [comment]
Yeah, I think "As a representative of an open source project or group" sounds better. Good enough. I'm curious what other people think. Closing.
