### ISSUE TITLE
is completely open communication realisitic for co-located teams? security?

### ISSUE THREAD

**Issue by pdurbin** [good-labs/greater-good-affirmation#12]
As of 8d3a317 the pledge says, "The community must have completely open communication, meaning all discussion around development is public." This sound great until you realize that a co-locate team is going to:

- hang around the water cooler and chat
- chat during standup
- have meetings without you, the person on the internet

I'm a big fan of overcommunicating as much as possible to people who aren't in the room but I'm not sure the the current phrasing is realistic.

In addition, security concerns should not be discussed in the open.

**Comment by vsoch** [comment]
How would you suggest we reword it? Just remove "completely" ?

**Comment by vsoch** [comment]
I changed the wording to say open communication about incentives - take a look https://good-labs.github.io/greater-good-pledge/pledge/

**Comment by vsoch** [comment]
Changed to:

> The community strives for open communication for discussion around development.

**Comment by pdurbin** [comment]
Making it "strives" is much better. Thanks! Closing.
