### ISSUE TITLE
maintainance of README.md vs GREATER_GOOD_PLEDGE.md

### ISSUE THREAD

**Issue by pdurbin** [good-labs/greater-good-affirmation#13]
As of 562ba07 README.md vs GREATER_GOOD_PLEDGE.md seem to have a lot of duplicate content. Will it be hard to keep them in sync?

**Comment by vsoch** [comment]
This is a good point (and one I've thought about) I'm thinking that we both want to have the content there (so someone can add the file if desired to their repo) but also be consistent between the web interface.

I'm going to try some tricks to (again) see if I can pipe the content into the web interface. The trick will be using javascript to handle the markdown. I'll take a look at your other PRs first in case they need to be merged

**Comment by vsoch** [comment]
Okay, this is fixed. You are definitely right that we don't want redundancy, it's confusing for the reader too. I've turned the README.md into more of a summary for the pledge, see 

https://github.com/good-labs/greater-good-pledge/commit/822f442f2b181c0185a0c15a43169a5f36c3b069

and now the pledge itself will be from GREATER_GOOD_PLEDGE.md. That's also what feeds into the web interface now. I've resolved this issue so I'm closing, please re-open if necessary!

**Comment by pdurbin** [comment]
Looks better. Thanks.
